### ISSUE TITLE
'IndexError: list index out of range' on v0.18.3

### ISSUE THREAD

**Issue by zoedberg** [nelfin/pylint-protobuf#39]
Using pylint-protobuf `v0.18.3` the pylint process fails with the following error:
```
Traceback (most recent call last):
  File "setup.py", line 435, in <module>
    'sdist': Sdist,
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 358, in run
    PylintRun(PYLINT_ARGS, do_exit=False)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 863, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1055, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint_protobuf/__init__.py", line 129, in visit_call
    self._check_repeated_scalar(node)
  File "/home/myuser/.virtualenvs/my-env/lib/python3.7/site-packages/pylint_protobuf/__init__.py", line 238, in _check_repeated_scalar
    c = c[0]
IndexError: list index out of range
```

Using pylint-protobuf `v0.17.0` on the same code works ok.

**Comment by nelfin** [comment]
I thought I had tests for this case but it turns out I had a couple of typos in the tests. Can you double-check that this fix works for your case?

**Comment by nelfin** [comment]
I've released the fixes in 853110d in `v0.18.4`
